server:
  port: 1515
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1717/eureka/
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:1919/oauth/user